FROM microsoft/aspnet

RUN apt-get install git -y 
RUN mkdir repositories
WORKDIR repositories

RUN git clone https://github.com/SogetiSpain/OWIN.Docker.git
WORKDIR OWIN.Docker/src

RUN nuget restore OWIN.Docker.sln
RUN xbuild OWIN.Docker.sln
EXPOSE 9000 
CMD mono OWIN.Docker/bin/Debug/OWIN.Docker.exe